import { PlusSquareOutlined } from '@ant-design/icons';

export const ArrCategories = [
	{name: "Danh mục", sub: [
		{name: "Danh mục loại khách hàng", icon: <PlusSquareOutlined />, link: "/"},
		{name: "Danh mục khách hàng", icon: <PlusSquareOutlined />, link: "/"},
		{name: "Danh mục hãng khai thác", icon: <PlusSquareOutlined />, link: "/"},
		{name: "Danh mục kích cỡ", icon: <PlusSquareOutlined />, link: "/category/container"},
		{name: "Danh mục công việc", icon: <PlusSquareOutlined />, link: "/"},
		{name: "Danh mục phương án công việc", icon: <PlusSquareOutlined />, link: "/category/job-mode"},
		{name: "Danh mục loại hàng hóa", icon: <PlusSquareOutlined />, link: "/"},
		{name: "Danh mục cảng", icon: <PlusSquareOutlined />, link: "/"},
		{name: "Danh mục tàu", icon: <PlusSquareOutlined />, link: "/"},
		{name: "Danh mục IMO", icon: <PlusSquareOutlined />, link: "/"},
		{name: "Danh mục cấu hình hàng hoá", icon: <PlusSquareOutlined />, link: "/category/commodity"},
		{name: "Danh mục quốc gia", icon: <PlusSquareOutlined />, link: "/"},
		{name: "Danh mục ngôn ngữ", icon: <PlusSquareOutlined />, link: "/category/language"},
	]},
	{name: "Biểu cước", sub: [
		{name: "Biểu cước chuẩn", icon: <PlusSquareOutlined />, link: "/"},
		{name: "Hợp đồng giảm giá", icon: <PlusSquareOutlined />, link: "/"},
		{name: "Biểu cước bậc thang", icon: <PlusSquareOutlined />, link: "/"},
	]},
	{name: "Cấu hình", sub: [
		{name: "Cấu hình duyệt lệnh", icon: <PlusSquareOutlined />, link: ""},
		{name: "Cấu hình miễn lưu bãi ngày lễ", icon: <PlusSquareOutlined />, link: ""},
		{name: "Cấu hình lưu bãi", icon: <PlusSquareOutlined />, link: ""},
		{name: "Cấu hình sử dụng điện", icon: <PlusSquareOutlined />, link: "/config/refer"},
		{name: "Cấu hình dịch vụ đính kèm", icon: <PlusSquareOutlined />, link: ""},
		{name: "Cấu hình phương thức thanh toán", icon: <PlusSquareOutlined />, link: ""},
		{name: "Cấu hình timeslot", icon: <PlusSquareOutlined />, link: ""},
		{name: "Cấu hình mail", icon: <PlusSquareOutlined />, link: ""},
		{name: "Cấu hình cảng", icon: <PlusSquareOutlined />, link: ""},
		{name: "Quản lý SFTP", icon: <PlusSquareOutlined />, link: ""},
	]},
	{name: "Tác nghiệp", sub: [
		{name: "Lệnh giao container hàng", icon: <PlusSquareOutlined />, link: ""},
		{name: "Lệnh giao container rỗng", icon: <PlusSquareOutlined />, link: ""},
		{name: "Lệnh hạ container hàng", icon: <PlusSquareOutlined />, link: ""},
		{name: "Lệnh hạ container rỗng", icon: <PlusSquareOutlined />, link: ""},
		{name: "Lệnh đóng hàng", icon: <PlusSquareOutlined />, link: ""},
		{name: "Lệnh rút hàng", icon: <PlusSquareOutlined />, link: ""},
		{name: "Lệnh dịch vụ", icon: <PlusSquareOutlined />, link: ""},
		{name: "Đăng ký tách lô từ Master Bill", icon: <PlusSquareOutlined />, link: ""},
		{name: "Phân bổ nhà xe", icon: <PlusSquareOutlined />, link: ""},
	]},
	{name: "Quản lý lệnh", sub: []},
	{name: "Hãng tàu", sub: []},
	{name: "Hải quan", sub: []},
	{name: "Công cụ", sub: []},
	{name: "Tra cứu", sub: []},
	{name: "Thống kê - báo cáo", sub: []},
	{name: "Quản trị hệ thống", sub: []}
]
